# app.yaml

application: davsknet
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /images
  static_dir: static/images

- url: /components
  static_dir: static/components

- url: /elements
  static_dir: static/elements

- url: /(.*\.(gif|png|jpg|ico|html|css))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|ico|html|css)$

- url: /profile/.*
  script: _go_app
  login: required

- url: /admin/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\.md$
- ^(.*/)?\.json$
